import { Inter } from "next/font/google";
import "./globals.scss";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
    <head>
      <title>MIS</title>
    </head>
    <body className={inter.variable}>
      <React.Fragment>
        {/* <Navbar /> */}
        {children}
      </React.Fragment>
    </body>
  </html>
  );
}
